03_Implementacao/django-weather/main/urls.py
"""main URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
"""
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from accounts import views as a
from stations import views as s
from events import views as e

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', s.home, name='home'), # all stations
    path('accounts/login/', a.UpdatedLoginView.as_view(), name='login'),
    path('accounts/logout/', a.logout, name='logout'),
    #path('accounts/password_reset/', a.password_reset, name='password-reset'),
    path('accounts/signup/', a.signup, name='signup'),
    path('accounts/activate/<uidb64>/<token>/', a.activate, name='activate'),
    path('events/', e.event_list, name='event-list'),
    path('events/add/', e.EventCreateView.as_view(), name='event-add'),
    path('events/<int:pk>/update/', e.EventUpdateView.as_view(), name='event-update'),
    path('events/<int:pk>/delete/', e.EventDeleteView.as_view(), name='event-delete'),
    path('stations/', s.station_list, name='station-list'),
    path('stations/search/', s.station_search, name='station-search'),
    path('stations/add/', s.StationCreateView.as_view(), name='station-add'),
    path('stations/<str:pk>/', s.StationDetailView.as_view(), name='station-detail'),
    path('stations/<str:pk>/update/', s.StationUpdateView.as_view(), name='station-update'),
    path('stations/<str:pk>/delete/', s.StationDeleteView.as_view(), name='station-delete'),
    path('get_user_location', s.get_user_location, name='get_user_location'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

03_Implementacao/django-weather/events/models.py
from stations.models import Station
from django.contrib.gis.db import models
#from django.contrib.postgres.fields.ranges import DateTimeRangeField
#from django.contrib.postgres.fields import DateTimeRangeField
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib import admin

SIGN_CHOICES = [
    ('lt', 'less than'),
    ('lte', 'less than or equal to'),
    ('eq', 'equal to'),
    ('gte', 'greater than or equal to'),
    ('gt', 'greater than'),
]

TYPE_CHOICES = [
    ("tmp", "Temperature"),
    ("hum", "Relative humidity"),
    ("atm", "Atmospheric pressure"),
    ("ws", "Wind speed"),
    ("wd", "Wind direction"),
    ("pre", "Precipitation"),
] # get from database?

class Event(models.Model):
    # automatic id primary key
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    measure_type = models.CharField(max_length=8, choices=TYPE_CHOICES)
    condition_sign = models.CharField(max_length=32, choices=SIGN_CHOICES)
    condition_value = models.FloatField()
    time_start = models.TimeField()
    time_end = models.TimeField()
    #is_active = models.BooleanField(default=True)

    #def get_absolute_url(self):
    #    return reverse('event-detail', kwargs={'pk': self.pk})

    class Meta:
        db_table = 'events'

admin.site.register(Event)

03_Implementacao/django-weather/events/forms.py
from django import forms
from .models import Event
from stations.models import Station

class EventForm(forms.ModelForm):

        def __init__(self, *args, **kwargs):
                user = kwargs.pop('user')

                super(EventForm, self).__init__(*args, **kwargs)
                self.fields['station'].queryset=Station.objects.filter(owner=user.id)
                self.creator = user

                input_classes = "text-gray-800 block w-full px-4 py-3 mb-4 border border-transparent border-gray-200 rounded-lg focus:ring focus:ring-indigo-400 focus:outline-none"
                self.fields['station'].widget.attrs['class'] = \
                                self.fields['measure_type'].widget.attrs['class'] = \
                                        self.fields['condition_sign'].widget.attrs['class'] = \
                                                self.fields['condition_value'].widget.attrs['class'] = \
                                                        self.fields['time_start'].widget.attrs['class'] = \
                                                                self.fields['time_end'].widget.attrs['class'] = input_classes          

        class Meta:
                fields = ['station', 'measure_type', 'condition_sign', 'condition_value', 'time_start', 'time_end']
                model = Event
                widgets = {'time_start': forms.TimeInput(attrs={'type': 'time'}), 'time_end': forms.TimeInput(attrs={'type': 'time'})}

03_Implementacao/django-weather/events/views.py
from django.shortcuts import render
from django.urls.base import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .models import Event
from .forms import EventForm
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import UserPassesTestMixin

@login_required
def event_list(request):
    event_list = Event.objects.filter(creator=request.user)
    
    context = {
        'events': event_list,
    }
    return render(request, 'events/event_list.html', context)

@method_decorator(login_required, name='dispatch')
class EventCreateView(CreateView):
    model = Event
    form_class = EventForm
    success_url = reverse_lazy('event-list')

    def get_form_kwargs(self):
        kwargs = super(EventCreateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

@method_decorator(login_required, name='dispatch')
class EventUpdateView(UserPassesTestMixin, UpdateView):
    model = Event
    form_class = EventForm
    success_url = reverse_lazy('event-list')

    def get_form_kwargs(self):
        kwargs = super(EventUpdateView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs
    
    def test_func(self):
        user = self.request.user
        return user == self.get_object().creator or user.is_staff

@method_decorator(login_required, name='dispatch')
class EventDeleteView(UserPassesTestMixin, DeleteView):
    model = Event
    success_url = reverse_lazy('event-list')

    def test_func(self):
        user = self.request.user
        return user == self.get_object().creator or user.is_staff

03_Implementacao/django-weather/main/templates/events/event_confirm_delete.html
{% extends 'base.html' %}

{% block title %}WSM Delete Event{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    <p class="text-2xl text-center">Are you sure you want to delete "{{ object }}"?</p>
    <button type="submit" class="cursor-pointer focus:ring focus:ring-indigo-400 focus:outline-none w-full px-3 py-4 font-medium text-white border border-transparent bg-gradient-to-r from-green-400 to-blue-400 rounded-lg">Confirm</button>
</form>
{% endblock %}

03_Implementacao/django-weather/main/templates/events/event_form.html
{% extends 'base.html' %}

{% block title %}WSM Create/Update Event{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    <div class="max-w-5xl mx-auto">
        <div class="flex flex-col items-center lg:flex-row">
        <div class="w-full mt-8 lg:w-1/2 mx-auto">
            <div class="bg-gray-700 relative z-10 h-auto p-8 py-10 overflow-hidden rounded-lg shadow-2xl px-7">
                {{ form.as_p }}
                <button type="submit" class="cursor-pointer focus:ring focus:ring-indigo-400 focus:outline-none w-full px-3 py-4 font-medium text-white border border-transparent bg-gradient-to-r from-green-400 to-blue-400 rounded-lg">Confirm</button>
            </div>
        </div>
        </div>
    </div>
</form>
{% endblock %}

03_Implementacao/django-weather/main/templates/events/event_list.html
{% extends 'base.html' %}

{% block title %}WSM Event List{% endblock %}

{% block content %}
<div class="w-full px-8 py-16">
	<div class="max-w-5xl mx-auto">
		<div class="w-full mt-8 mx-auto overflow-hidden lg:overflow-visible">
            <h1 class="text-center text-xl font-extrabold tracking-wide">Your Events</h1>
			<table style="border-spacing: 0px 2em;" class="w-full table table-fixed border-separate overflow-visible space-y-8 text-xs lg:text-sm">
				<thead>
					<tr class="text-left bg-gradient-to-r from-green-300 to-blue-300 text-gray-700 break-words overflow-hidden shadow-lg">
						<th class="w-1/6 rounded-l-lg p-3">Station</th>
                        <th class="text-right w-1/6 p-3">Measure Type</th>
                        <th class="text-center w-1/6 p-3">Condition Sign</th>
                        <th class="w-1/6 p-3">Condition Value</th>
                        <th class="w-1/6 p-3">Time Range</th>
                        <th class="text-center w-1/6 rounded-r-lg p-3">Actions</th>
					</tr>
				</thead>
				<tbody>
					{% for ev in events %}
					<tr onclick="window.location='{{ ev.get_absolute_url }}';" class="text-left bg-gray-700 overflow-hidden shadow-lg">
						<td class="rounded-l-lg p-3 transition duration-150 ease-out hover:text-white" x-data="{ hover: false }">{{ ev.station_id }}</td>
                        <td class="text-right p-3 transition duration-150 ease-out hover:text-white" x-data="{ hover: false }">{{ ev.get_measure_type_display }}</td>
						<td class="text-center p-3 transition duration-150 ease-out hover:text-white" x-data="{ hover: false }">{{ ev.get_condition_sign_display }}</td>
                        <td class="p-3 transition duration-150 ease-out hover:text-white" x-data="{ hover: false }">{{ ev.condition_value }}</td>
                        <td class="p-3 transition duration-150 ease-out hover:text-white" x-data="{ hover: false }">{{ ev.time_start }} - {{ ev.time_end }}</td>
						<td class="flex flex-row justify-center rounded-r-lg p-3 transition duration-150 ease-out hover:text-white" x-data="{ hover: false }">
                            <!--<a href="#" class="text-blue-300 transition duration-150 ease-out hover:text-white">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <title>Subscribe</title>
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
                                </svg>
							</a>-->
							<a href="{% url 'event-update' pk=ev.pk %}" class="text-blue-300 transition duration-150 ease-out hover:text-white">
								<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <title>Edit</title>
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                </svg>
							</a>
							<a href="{% url 'event-delete' pk=ev.pk %}" class="text-blue-300 transition duration-150 ease-out hover:text-white">
								<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <title>Delete</title>
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                </svg>
							</a>
                        </td>
					</tr>
					{% endfor %}
                    <tr class="text-left bg-gray-700 overflow-hidden shadow-lg">
						<td class="rounded-l-lg p-3 transition duration-150 ease-out hover:text-white" x-data="{ hover: false }">
                            <a href="{% url 'event-add' %}" class="text-green-300 transition duration-150 ease-out hover:text-white">
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <title>Add new</title>
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                                </svg>
                            </a>
                        </td>
                        <td class="p-3"></td>
						<td class="p-3"></td>
                        <td class="p-3"></td>
                        <td class="p-3"></td>
						<td class="rounded-r-lg p-3">
                        </td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

03_Implementacao/django-weather/main/templates/events/event_triggered.html
{% autoescape off %}
{{ event.get_measure_type_display }} is {{ event.get_condition_sign_display }} {{ event.condition_value }} on station {{ event.station }}!
{% endautoescape %}